# SPDX-License-Identifier: GPL-3.0-or-later

ISO = https://cdimage.debian.org/cdimage/daily-builds/daily/arch-latest/amd64/iso-cd/debian-testing-amd64-netinst.iso
VM_ROOTFS = /dev/vda2

include ../mk/amd64.mk
