# SPDX-License-Identifier: GPL-3.0-or-later

ISO = https://cdimage.debian.org/cdimage/daily-builds/daily/arch-latest/riscv64/iso-cd/debian-testing-riscv64-netinst.iso
VM_ROOTFS = /dev/vda2

include ../mk/riscv64.mk
