# SPDX-License-Identifier: GPL-3.0-or-later

ISO = https://cdimage.debian.org/mirror/cdimage/archive/12.12.0/i386/iso-cd/debian-12.12.0-i386-netinst.iso
ifndef VM_BIOS
VM_ROOTFS = /dev/vda2
endif

include ../mk/i686.mk
