# SPDX-License-Identifier: GPL-3.0-or-later

ISO = https://cdimage.debian.org/cdimage/daily-builds/daily/arch-latest/arm64/iso-cd/debian-testing-arm64-netinst.iso
VM_ROOTFS = /dev/vda2

include ../mk/arm64.mk
