#
# Makefile for qemu-system-x86_64
#
# Sane defaults for basic install and boot scenarios
#

HDD = CentOS-7-x86_64.img
ISO = http://mirror.ox.ac.uk/sites/mirror.centos.org/7.9.2009/isos/x86_64/CentOS-7-x86_64-DVD-2009.iso

include ../mk/amd64.mk
