# SPDX-License-Identifier: GPL-3.0-or-later

ISO = https://cdimage.debian.org/mirror/cdimage/archive/13.1.0/riscv64/iso-cd/debian-13.1.0-riscv64-netinst.iso
VM_ROOTFS = /dev/vda2

include ../mk/riscv64.mk
