# SPDX-License-Identifier: GPL-3.0-or-later

ISO = https://cdimage.debian.org/mirror/cdimage/archive/12.12.0/arm64/iso-cd/debian-12.12.0-arm64-netinst.iso
VM_ROOTFS = /dev/vda2

include ../mk/arm64.mk
